name: NuGet Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release  
    - name: Pack
      run: dotnet pack -c Release  
    - name: Extract version number
      id: extract_version
      run: |
        version=$(grep -oPm1 "(?<=<Version>)[^<]+" Luzyce.Core/Luzyce.Core.csproj)
        echo "version=$version" >> $GITHUB_ENV
    - name: Push to GitHub Packages
      run: |
        dotnet nuget add source --username ddnowicki --password "${{ secrets.NUGET_PACKAGE_TOKEN }}" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ddnowicki/index.json"
        dotnet nuget push Luzyce.Core/bin/Release/Luzyce.Core.${{ env.version }}.nupkg --api-key "${{ secrets.NUGET_PACKAGE_TOKEN }}" -s https://nuget.pkg.github.com/ddnowicki/index.json
