name: NuGet Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release  
    - name: Pack
      run: dotnet pack -c Release  
    - name: Extract version number
      id: extract_version
      run: echo "##[set-output name=version;]$(grep -oPm1 "(?<=<Version>)[^<]+" /Luzyce.Core/Luzyce.Core.csproj)"
    - name: Push
      run: dotnet nuget push /Luzyce.Core/bin/Release/Luzyce.Core.${{ steps.extract_version.outputs.version }}.nupkg -k "${{ secrets.NUGET_PUBLISH_KEY }}" -s https://api.nuget.org/v3/index.json
